theme: jekyll-theme-midnight # jekyll-theme-tactile
title: Statistics Tidbits
description: >- # this means to ignore newlines until "baseurl:"
  Blog about statistics, data science, data engineering and machine learning. 
  Posts will be my random thoughts about the industry. Some technical, some not.
baseurl: "/docs" # the subpath of your site, e.g. /blog
domain: statisticstidbits.com
url: "https://statisticstidbits.com/" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

